### PR TITLE
Elhalwagui-CarAgency

### PR DESCRIPTION
**Pull request by ElhalwaguiAhmedMohamed**
Hello, Mohamed
I managed to build the business logic using the required tools but had some problems creating the tests as those tools were new to me so I took some time to figure out the big picture of the tools working together. I tried to do the tests using type-ORM but I had already used Mikro-ORM with the resolvers so it didn't work. I couldn't find good resources to do the tests with Mikro-ORM and type-graphql. I hope you can give me any feedback on that or a good resource to see.
thank you for letting me try new things and I hope to see you again soon.

### CODE REVIEW

**Comment by maramizo** [comment]
Interesting, didn't you already have tests embedded in your previous project?
@ElhalwaguiAhmedMohamed

**Comment by ElhalwaguiAhmedMohamed** [comment]
Yes, but it wasn't for type graphql and mikro-orm.
I tried to create a connection before all the tests on a new data base for testing and after all the tests I wanted to drop the database data.
but I couldn't reach wasn't able to properly test the resolvers.

**Comment by maramizo** [comment]
https://github.com/Hoarsecords/CarAgencyOnGraphQL/tree/testable-base
Rebase your fork on this branch - I've added a base of tests there for you under resolvers/__tests__.
Note that this tests both entities and resolvers which is unreasonable given it's placed under resolvers/ and will need to be refactored.
@ElhalwaguiAhmedMohamed

**Comment by maramizo** [comment]
Also note I've edited some of your code under customerResolvers just to create the tests in the first place.

**Comment by ElhalwaguiAhmedMohamed** [comment]
Ok thank you I'll check it out

**Comment by maramizo** [comment]
I'm pushing your deadline to the 20th by the way, this way you'll have enough time to set this up given you have the necessary framework.

**Comment by ElhalwaguiAhmedMohamed** [comment]
Ok, thank you I'll do my best

**Comment by ElhalwaguiAhmedMohamed** [comment]
> https://github.com/Hoarsecords/CarAgencyOnGraphQL/tree/testable-base
> Rebase your fork on this branch - I've added a base of tests there for you under resolvers/__tests__.
> Note that this tests both entities and resolvers which is unreasonable given it's placed under resolvers/ and will need to be refactored.
> @ElhalwaguiAhmedMohamed 

I was just trying to test just the resolvers here not the entities

**Pull request closed without merging**
